### ISSUE TITLE
How to trim the blank lines with <%= %> expressions

### ISSUE THREAD

**Issue by beviz** [ruby/erb#24]
ERB supports to use `trim_mode: '-'` to trim the blank lines, including `<%-` to trim the previous line and `-%>` to trim the following.

Now I have a scenario to output one line in a yaml file. I want to shorten the following multiple lines 

```YAMl
repos:
  - repo: https://github.com/repo1
    hooks:
      - hook_1
      <%- if condition -%>
      - hook2
      <%- end -%>
      <%- if condition -%>
      - hook3
      <%- end -%>
```

to 

```YAML
repos:
  - repo: https://github.com/repo1
    hooks:
      - hook_1
      <%-= '- hook2' if condition -%>
      <%-= '- hook3' if condition -%>
```

But ERB doesn't yet support such a `<%-=` corresponding to `<%-`.

Team, can you please add this feature? It would become more consistent and convenient.
